"""Localization constants separated from core logic."""

RESEARCH_AREA_ICONS = {
    "physics": "£physics£",
    "engineering": "£engineering£",
    "society": "£society£"
}

LOCALIZATION_STRINGS = {
    "english": {
        "title": "Technology Tree",
        "top_level": "Maximum Level Reached",
        "requires": "Requires",
        "tier_label": "Tier:",
        "already_shown": "already shown above",
        "skip_long_tree": "Too many follow-up technologies. Not displayed for performance.",
        "folded_more": "(and {count} more technologies)",
        "root_children_exceed_limit": "Root direct children exceed global display limit; cannot display tree",
        "global_overflow_reached": "(and {count} more technologies hidden globally)",
        "msg_start_generation": "Generating technology tree MOD...",
        "msg_counting_tree": "Computing technology tree sizes...",
        "msg_enabled_mods_count": "Enabled MOD count: {count}",
        "msg_missing_mod_dirs": "Notice: {count} enabled MOD directories are missing",
        "msg_mods_with_new_techs": "Notice: {count} enabled MOD(s) added technologies",
        "warn_missing_dlc_load": "Warning: dlc_load.json not found: {path}",
        "warn_read_dlc_load_failed": "Warning: failed to read dlc_load.json: {error}",
        "warn_write_file_failed": "Warning: cannot write file {file}: {error}",
        "warn_tech_parse_summary": "Notice: scanned {total} tech files; ok={ok}; failed={failed} (showing {shown}, suppressed {suppressed})",
        "warn_tech_parse_failure_example": "  Tech parse failed: {path} — {error}",
        "warn_loc_parse_summary": "Notice: scanned {total} localisation files; ok={ok}; failed={failed} (showing {shown}, suppressed {suppressed})",
        "warn_loc_parse_failure_example": "  Localisation parse failed: {path} — {error}",
        "warn_read_file_failed_summary": "Warning: failed to read {failed} file(s) (showing {shown}, suppressed {suppressed})",
        "warn_read_file_failed_example": "  Read failed: {path} — {error}",
        "warn_missing_descriptions": "Warning: {lang} language has {count} technologies missing descriptions",
        "stats_header": "Generation Statistics:",
        "stats_total": "Total techs: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localized ({lang}): {count}",
        "stats_overlong": "Overlong trees (>{threshold} successors): {count} — not displayed in game",
        "overbreadth_zero": "Over-breadth roots: 0 (T={threshold})",
        "overbreadth_list_header": "Over-breadth roots list (direct children > T):",
        "overbreadth_entry": "  {tech_id}  (children={child_count} > T={threshold})",
        "overbreadth_truncated": "  ... ({remaining} more)",
        "msg_generation_done": "Generation finished!",
        "error_missing_config": "Error: config file {path} not found",
        "error_config_paths": "Ensure config.ini exists with correct path settings",
        "prompt_press_enter": "Press Enter to exit.",
        "msg_detecting_cycles": "Detecting technology circular dependencies...",
        "msg_cycles_found": "Found {count} cycle(s):",
        "msg_self_loops_header": "  Self loops ({count}):",
        "msg_complex_loops_header": "  Complex cycles ({count}):",
        "msg_cycle_entry": "    Cycle {index}: {cycle}",
        "msg_no_cycles": "No circular dependencies found.",
        "warn_language_not_supported": "Warning: language '{lang}' not in LANGUAGE_KEY_MAP, falling back to english"
        ,"error_generation_exception": "Error during generation: {error}"
    ,"error_missing_localization_section": "Error: missing [localization] section"
        ,"error_missing_required_entries": "Error: required configuration entries missing: {error}"
        ,"hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms."
        ,"msg_priority_localization_mods": "Priority localization MODs: {count}"
        ,"msg_self_loop_entry": "    {tech} -> {tech}"
    },
    "simp_chinese": {
        "title": "科技树",
        "top_level": "已达到顶级",
        "requires": "还需",
        "tier_label": "级别:",
        "already_shown": "已在上方展示",
        "skip_long_tree": "后续科技太多，性能原因不做展示",
        "folded_more": "(后续还有{count}个科技)",
        "root_children_exceed_limit": "此科技直接子科技数量超过上限，无法展示此树",
        "global_overflow_reached": "(后续还有{count}个科技)",
        "msg_start_generation": "正在生成科技树MOD...",
        "msg_counting_tree": "正在统计科技树规模...",
        "msg_enabled_mods_count": "启用MOD数量: {count}",
        "msg_missing_mod_dirs": "提示: 有 {count} 个启用MOD目录缺失",
        "msg_mods_with_new_techs": "提示: 有 {count} 个启用MOD有新增科技",
        "warn_missing_dlc_load": "警告: 找不到 dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "警告: 读取 dlc_load.json 失败: {error}",
        "warn_write_file_failed": "警告：无法写入文件 {file}: {error}",
        "warn_tech_parse_summary": "提示: 扫描科技文件 {total} 个；成功 {ok}；失败 {failed}（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_tech_parse_failure_example": "  科技解析失败: {path} — {error}",
        "warn_loc_parse_summary": "提示: 扫描本地化文件 {total} 个；成功 {ok}；失败 {failed}（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_loc_parse_failure_example": "  本地化解析失败: {path} — {error}",
        "warn_read_file_failed_summary": "警告: 读取文件失败 {failed} 个（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_read_file_failed_example": "  读取失败: {path} — {error}",
        "warn_missing_descriptions": "警告: {lang} 语言有 {count} 个科技缺失描述",
        "stats_header": "生成统计:",
        "stats_total": "科技总数: {total} (本体: {base}, MOD: {mod})",
        "stats_localization": "本地化({lang}): {count}个",
        "stats_overlong": "超长科技树(>{threshold} 后续科技) 数量: {count} —— 游戏内不予展示",
        "overbreadth_zero": "超宽根节点: 0 (T={threshold})",
        "overbreadth_list_header": "超宽根节点列表 (直接子科技 > T):",
        "overbreadth_entry": "  {tech_id}  (子科技数={child_count} > T={threshold})",
        "overbreadth_truncated": "  ... (剩余 {remaining} 个)",
        "msg_generation_done": "生成完成！",
        "error_missing_config": "错误: 配置文件 {path} 不存在",
        "error_config_paths": "请确保config.ini文件存在并包含正确的路径配置",
        "prompt_press_enter": "按 Enter 键退出。",
        "msg_detecting_cycles": "正在检测科技循环依赖...",
        "msg_cycles_found": "发现 {count} 个循环依赖:",
        "msg_self_loops_header": "  自循环科技 ({count}个):",
        "msg_complex_loops_header": "  复杂循环 ({count}个):",
        "msg_cycle_entry": "    循环 {index}: {cycle}",
        "msg_no_cycles": "未发现循环依赖。",
        "warn_language_not_supported": "警告: 语言 '{lang}' 未在映射表中, 回退为 english"
        ,"error_generation_exception": "生成过程中出现错误: {error}"
    ,"error_missing_localization_section": "错误: 缺少 [localization] 配置节"
        ,"error_missing_required_entries": "错误: 缺少必要配置项: {error}"
        ,"hint_missing_dlc_path_non_windows": "提示: 未设置 dlc_load_path；请在非 Windows 平台显式配置。"
        ,"msg_priority_localization_mods": "优先本地化 MOD 数量: {count}"
        ,"msg_self_loop_entry": "    {tech} -> {tech}"
    },
    "french": {
        "title": "Arbre Technologique",
        "top_level": "Niveau maximum atteint",
        "requires": "Requiert",
        "tier_label": "Niveau:",
        "already_shown": "déjà affiché ci-dessus",
        "skip_long_tree": "Trop de technologies suivantes. Non affiché pour les performances.",
        "msg_start_generation": "Génération du MOD d'arbre technologique...",
        "msg_counting_tree": "Calcul de la taille des arbres technologiques...",
        "msg_enabled_mods_count": "Nombre de MODs activés : {count}",
        "msg_missing_mod_dirs": "Remarque : {count} dossiers de MOD activés manquent",
        "msg_mods_with_new_techs": "Remarque : {count} MOD(s) ont ajouté des technologies",
        "warn_missing_dlc_load": "Avertissement : dlc_load.json introuvable : {path}",
        "warn_read_dlc_load_failed": "Avertissement : échec de lecture de dlc_load.json : {error}",
        "warn_write_file_failed": "Avertissement : impossible d'écrire le fichier {file} : {error}",
        "warn_missing_descriptions": "Avertissement : la langue {lang} a {count} technologies sans description",
        "stats_header": "Statistiques de génération :",
        "stats_total": "Total technologies : {total} (Base : {base}, MOD : {mod})",
        "stats_localization": "Localisé ({lang}) : {count}",
    "stats_overlong": "Arbres trop longs (>{threshold} successeurs) : {count} — non affichés en jeu",
        "msg_generation_done": "Génération terminée !",
        "error_missing_config": "Erreur : fichier de config {path} introuvable",
        "error_config_paths": "Assurez-vous que config.ini existe et contient les bons chemins",
        "prompt_press_enter": "Appuyez sur Entrée pour quitter.",
        "msg_detecting_cycles": "Détection des dépendances circulaires...",
        "msg_cycles_found": "Trouvé {count} cycle(s) :",
        "msg_self_loops_header": "  Boucles simples ({count}) :",
        "msg_complex_loops_header": "  Cycles complexes ({count}) :",
        "msg_cycle_entry": "    Cycle {index}: {cycle}",
        "msg_no_cycles": "Aucun cycle détecté.",
        "warn_language_not_supported": "Avertissement : langue '{lang}' non supportée, retour à english",
        "error_generation_exception": "Erreur pendant la génération : {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "german": {
        "title": "Technologiebaum",
        "top_level": "Maximale Stufe erreicht",
        "requires": "Benötigt",
        "tier_label": "Stufe:",
        "already_shown": "oben bereits angezeigt",
        "skip_long_tree": "Zu viele Folgetechnologien. Aus Leistungsgründen nicht angezeigt.",
        "msg_start_generation": "Generiere Technologiebaum-MOD...",
        "msg_counting_tree": "Berechne Technologiebaum-Größen...",
        "msg_enabled_mods_count": "Aktivierte MOD-Anzahl: {count}",
        "msg_missing_mod_dirs": "Hinweis: {count} aktivierte MOD-Verzeichnisse fehlen",
        "msg_mods_with_new_techs": "Hinweis: {count} MOD(s) fügten Technologien hinzu",
        "warn_missing_dlc_load": "Warnung: dlc_load.json nicht gefunden: {path}",
        "warn_read_dlc_load_failed": "Warnung: Lesen von dlc_load.json fehlgeschlagen: {error}",
        "warn_write_file_failed": "Warnung: Datei {file} kann nicht geschrieben werden: {error}",
        "warn_missing_descriptions": "Warnung: Sprache {lang} hat {count} Technologien ohne Beschreibung",
        "stats_header": "Generierungsstatistiken:",
        "stats_total": "Technologien gesamt: {total} (Basis: {base}, MOD: {mod})",
        "stats_localization": "Lokalisiert ({lang}): {count}",
    "stats_overlong": "Zu lange Bäume (>{threshold} Nachfolger): {count} — nicht im Spiel angezeigt",
        "msg_generation_done": "Generierung abgeschlossen!",
        "error_missing_config": "Fehler: Konfigurationsdatei {path} nicht gefunden",
        "error_config_paths": "Stellen Sie sicher, dass config.ini existiert und korrekt konfiguriert ist",
        "prompt_press_enter": "Drücken Sie Enter zum Beenden.",
        "msg_detecting_cycles": "Suche nach zyklischen Abhängigkeiten...",
        "msg_cycles_found": "{count} Zyklen gefunden:",
        "msg_self_loops_header": "  Selbstschleifen ({count}):",
        "msg_complex_loops_header": "  Komplexe Zyklen ({count}):",
        "msg_cycle_entry": "    Zyklus {index}: {cycle}",
        "msg_no_cycles": "Keine Zyklen gefunden.",
        "warn_language_not_supported": "Warnung: Sprache '{lang}' nicht unterstützt, fallback zu english",
        "error_generation_exception": "Fehler während der Generierung: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "spanish": {
        "title": "Árbol Tecnológico",
        "top_level": "Nivel Máximo Alcanzado",
        "requires": "Requiere",
        "tier_label": "Nivel:",
        "already_shown": "ya mostrado arriba",
        "skip_long_tree": "Demasiadas tecnologías posteriores. No se muestra por rendimiento.",
        "msg_start_generation": "Generando MOD del árbol tecnológico...",
        "msg_counting_tree": "Calculando tamaños del árbol tecnológico...",
        "msg_enabled_mods_count": "Cantidad de MODs habilitados: {count}",
        "msg_missing_mod_dirs": "Aviso: faltan {count} directorios de MOD habilitados",
        "msg_mods_with_new_techs": "Aviso: {count} MOD(s) añadieron tecnologías",
        "warn_missing_dlc_load": "Advertencia: no se encontró dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Advertencia: fallo al leer dlc_load.json: {error}",
        "warn_write_file_failed": "Advertencia: no se puede escribir el archivo {file}: {error}",
        "warn_missing_descriptions": "Advertencia: el idioma {lang} tiene {count} tecnologías sin descripción",
        "stats_header": "Estadísticas de generación:",
        "stats_total": "Tecnologías totales: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localizado ({lang}): {count}",
    "stats_overlong": "Árboles demasiado largos (>{threshold} sucesoras): {count} — no se muestran en el juego",
        "msg_generation_done": "¡Generación finalizada!",
        "error_missing_config": "Error: archivo de configuración {path} no encontrado",
        "error_config_paths": "Asegúrate de que config.ini exista y tenga rutas correctas",
        "prompt_press_enter": "Pulsa Enter para salir.",
        "msg_detecting_cycles": "Detectando dependencias cíclicas...",
        "msg_cycles_found": "Encontrado(s) {count} ciclo(s):",
        "msg_self_loops_header": "  Bucles simples ({count}):",
        "msg_complex_loops_header": "  Ciclos complejos ({count}):",
        "msg_cycle_entry": "    Ciclo {index}: {cycle}",
        "msg_no_cycles": "No se encontraron ciclos.",
        "warn_language_not_supported": "Advertencia: idioma '{lang}' no soportado, usando english",
        "error_generation_exception": "Error durante la generación: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "russian": {
        "title": "Древо технологий",
        "top_level": "Достигнут максимальный уровень",
        "requires": "Требуется",
        "tier_label": "Уровень:",
        "already_shown": "уже показано выше",
        "skip_long_tree": "Слишком много последующих технологий. Не показывается из-за производительности.",
        "msg_start_generation": "Генерация мода древа технологий...",
        "msg_counting_tree": "Подсчет размеров древ технологий...",
        "msg_enabled_mods_count": "Количество активных модов: {count}",
        "msg_missing_mod_dirs": "Примечание: отсутствует {count} каталог(ов) активных модов",
        "msg_mods_with_new_techs": "Примечание: {count} мод(ов) добавили технологии",
        "warn_missing_dlc_load": "Предупреждение: не найден dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Предупреждение: ошибка чтения dlc_load.json: {error}",
        "warn_write_file_failed": "Предупреждение: не удалось записать файл {file}: {error}",
        "warn_missing_descriptions": "Предупреждение: язык {lang} — {count} технологий без описания",
        "stats_header": "Статистика генерации:",
        "stats_total": "Всего технологий: {total} (База: {base}, Моды: {mod})",
        "stats_localization": "Локализовано ({lang}): {count}",
    "stats_overlong": "Слишком длинные деревья (>{threshold} потомков): {count} — не показываются в игре",
        "msg_generation_done": "Генерация завершена!",
        "error_missing_config": "Ошибка: файл конфигурации {path} не найден",
        "error_config_paths": "Убедитесь, что config.ini существует и содержит верные пути",
        "prompt_press_enter": "Нажмите Enter для выхода.",
        "msg_detecting_cycles": "Поиск циклических зависимостей...",
        "msg_cycles_found": "Найдено циклов: {count}",
        "msg_self_loops_header": "  Самоциклы ({count}):",
        "msg_complex_loops_header": "  Сложные циклы ({count}):",
        "msg_cycle_entry": "    Цикл {index}: {cycle}",
        "msg_no_cycles": "Циклов не обнаружено.",
        "warn_language_not_supported": "Предупреждение: язык '{lang}' не поддерживается, возврат к english",
        "error_generation_exception": "Ошибка в ходе генерации: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "korean": {
        "title": "기술 트리",
        "top_level": "최대 단계 도달",
        "requires": "요구",
        "tier_label": "단계:",
        "already_shown": "위에 이미 표시됨",
        "skip_long_tree": "후속 기술이 너무 많아 성능상 표시하지 않습니다.",
        "msg_start_generation": "기술 트리 MOD 생성 중...",
        "msg_counting_tree": "기술 트리 규모 계산 중...",
        "msg_enabled_mods_count": "활성 MOD 수: {count}",
        "msg_missing_mod_dirs": "알림: 활성 MOD 디렉터리 {count}개 누락",
        "msg_mods_with_new_techs": "알림: {count}개 MOD가 기술을 추가함",
        "warn_missing_dlc_load": "경고: dlc_load.json 을 찾을 수 없음: {path}",
        "warn_read_dlc_load_failed": "경고: dlc_load.json 읽기 실패: {error}",
        "warn_write_file_failed": "경고: 파일 {file} 을(를) 쓸 수 없음: {error}",
        "warn_missing_descriptions": "경고: {lang} 언어 기술 {count}개 설명 누락",
        "stats_header": "생성 통계:",
        "stats_total": "기술 총계: {total} (본체: {base}, MOD: {mod})",
        "stats_localization": "로컬라이즈됨 ({lang}): {count}",
    "stats_overlong": "너무 긴 트리 (>{threshold} 후속): {count} — 게임에서 표시 안 함",
        "msg_generation_done": "생성 완료!",
        "error_missing_config": "오류: 설정 파일 {path} 없음",
        "error_config_paths": "config.ini 가 존재하고 경로가 올바른지 확인",
        "prompt_press_enter": "종료하려면 Enter 키를 누르세요.",
        "msg_detecting_cycles": "순환 의존성 탐지 중...",
        "msg_cycles_found": "순환 {count}개 발견:",
        "msg_self_loops_header": "  자기 순환 ({count})",
        "msg_complex_loops_header": "  복잡한 순환 ({count})",
        "msg_cycle_entry": "    순환 {index}: {cycle}",
        "msg_no_cycles": "순환 없음.",
        "warn_language_not_supported": "경고: 언어 '{lang}' 지원 안 함, english 로 대체",
        "error_generation_exception": "생성 중 오류 발생: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "japanese": {
        "title": "技術ツリー",
        "top_level": "最大レベルに到達",
        "requires": "必要",
        "tier_label": "レベル:",
        "already_shown": "上で既に表示済み",
        "skip_long_tree": "後続技術が多すぎるため表示しません。",
        "msg_start_generation": "技術ツリーMOD生成中...",
        "msg_counting_tree": "技術ツリー規模を計算中...",
        "msg_enabled_mods_count": "有効MOD数: {count}",
        "msg_missing_mod_dirs": "注意: 有効なMODディレクトリ {count} 個が見つかりません",
        "msg_mods_with_new_techs": "注意: {count} 個のMODが技術を追加しました",
        "warn_missing_dlc_load": "警告: dlc_load.json が見つかりません: {path}",
        "warn_read_dlc_load_failed": "警告: dlc_load.json の読み込みに失敗: {error}",
        "warn_write_file_failed": "警告: ファイル {file} に書き込めません: {error}",
        "warn_missing_descriptions": "警告: 言語 {lang} で {count} 技術の説明が不足",
        "stats_header": "生成統計:",
        "stats_total": "技術総数: {total} (本体: {base}, MOD: {mod})",
        "stats_localization": "ローカライズ済 ({lang}): {count}",
    "stats_overlong": "長すぎるツリー (>{threshold} 派生): {count} — ゲーム内では表示されません",
        "msg_generation_done": "生成完了！",
        "error_missing_config": "エラー: 設定ファイル {path} がありません",
        "error_config_paths": "config.ini の存在とパス設定を確認してください",
        "prompt_press_enter": "Enter キーを押して終了",
        "msg_detecting_cycles": "循環依存を検出中...",
        "msg_cycles_found": "{count} 個の循環を検出:",
        "msg_self_loops_header": "  自己循環 ({count})",
        "msg_complex_loops_header": "  複雑な循環 ({count})",
        "msg_cycle_entry": "    循環 {index}: {cycle}",
        "msg_no_cycles": "循環は見つかりませんでした。",
        "warn_language_not_supported": "警告: 言語 '{lang}' は未対応のため english にフォールバック",
        "error_generation_exception": "生成中にエラーが発生しました: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "polish": {
        "title": "Drzewo Technologii",
        "top_level": "Osiągnięto maksymalny poziom",
        "requires": "Wymaga",
        "tier_label": "Poziom:",
        "already_shown": "już pokazano powyżej",
        "skip_long_tree": "Zbyt wiele kolejnych technologii. Nie wyświetlono ze względów wydajności.",
        "msg_start_generation": "Generowanie moda drzewa technologii...",
        "msg_counting_tree": "Obliczanie rozmiarów drzew technologii...",
        "msg_enabled_mods_count": "Liczba aktywnych modów: {count}",
        "msg_missing_mod_dirs": "Uwaga: brak {count} katalogów aktywnych modów",
        "msg_mods_with_new_techs": "Uwaga: {count} mod(y) dodały technologie",
        "warn_missing_dlc_load": "Ostrzeżenie: nie znaleziono dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Ostrzeżenie: błąd odczytu dlc_load.json: {error}",
        "warn_write_file_failed": "Ostrzeżenie: nie można zapisać pliku {file}: {error}",
        "warn_missing_descriptions": "Ostrzeżenie: język {lang} ma {count} technologii bez opisu",
        "stats_header": "Statystyki generowania:",
        "stats_total": "Łącznie technologii: {total} (Podstawa: {base}, Mody: {mod})",
        "stats_localization": "Zlokalizowano ({lang}): {count}",
    "stats_overlong": "Zbyt długie drzewa (>{threshold} następców): {count} — niewyświetlane w grze",
        "msg_generation_done": "Generowanie zakończone!",
        "error_missing_config": "Błąd: plik config {path} nie znaleziony",
        "error_config_paths": "Upewnij się, że config.ini istnieje i ma poprawne ścieżki",
        "prompt_press_enter": "Naciśnij Enter, aby wyjść.",
        "msg_detecting_cycles": "Wykrywanie zależności cyklicznych...",
        "msg_cycles_found": "Znaleziono cykli: {count}",
        "msg_self_loops_header": "  Pętle własne ({count}):",
        "msg_complex_loops_header": "  Złożone cykle ({count}):",
        "msg_cycle_entry": "    Cykl {index}: {cycle}",
        "msg_no_cycles": "Nie znaleziono cykli.",
        "warn_language_not_supported": "Ostrzeżenie: język '{lang}' nieobsługiwany, powrót do english",
        "error_generation_exception": "Błąd podczas generowania: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
    "braz_por": {
        "title": "Árvore de Tecnologia",
        "top_level": "Nível Máximo Atingido",
        "requires": "Requer",
        "tier_label": "Nível:",
        "already_shown": "já mostrado acima",
        "skip_long_tree": "Muitas tecnologias subsequentes. Não exibido por desempenho.",
        "msg_start_generation": "Gerando MOD da árvore de tecnologia...",
        "msg_counting_tree": "Calculando tamanhos da árvore de tecnologia...",
        "msg_enabled_mods_count": "Quantidade de MODs ativos: {count}",
        "msg_missing_mod_dirs": "Aviso: {count} diretórios de MOD ativos ausentes",
        "msg_mods_with_new_techs": "Aviso: {count} MOD(s) adicionaram tecnologias",
        "warn_missing_dlc_load": "Aviso: dlc_load.json não encontrado: {path}",
        "warn_read_dlc_load_failed": "Aviso: falha ao ler dlc_load.json: {error}",
        "warn_write_file_failed": "Aviso: não é possível gravar o arquivo {file}: {error}",
        "warn_missing_descriptions": "Aviso: idioma {lang} tem {count} tecnologias sem descrição",
        "stats_header": "Estatísticas de geração:",
        "stats_total": "Total de tecnologias: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localizado ({lang}): {count}",
    "stats_overlong": "Árvores muito longas (>{threshold} sucessoras): {count} — não exibidas no jogo",
        "msg_generation_done": "Geração concluída!",
        "error_missing_config": "Erro: arquivo de configuração {path} não encontrado",
        "error_config_paths": "Garanta que config.ini exista e tenha caminhos corretos",
        "prompt_press_enter": "Pressione Enter para sair.",
        "msg_detecting_cycles": "Detectando dependências circulares...",
        "msg_cycles_found": "Encontrados {count} ciclo(s)",
        "msg_self_loops_header": "  Auto-loops ({count})",
        "msg_complex_loops_header": "  Ciclos complexos ({count})",
        "msg_cycle_entry": "    Ciclo {index}: {cycle}",
        "msg_no_cycles": "Nenhum ciclo encontrado.",
        "warn_language_not_supported": "Aviso: idioma '{lang}' não suportado, usando english",
        "error_generation_exception": "Erro durante a geração: {error}",
    "hint_missing_dlc_path_non_windows": "Hint: dlc_load_path not set; please configure it explicitly on non-Windows platforms.",
        "msg_priority_localization_mods": "Priority localization MODs: {count}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    "error_missing_localization_section": "Error: missing [localization] section",
        "error_missing_required_entries": "Error: required configuration entries missing: {error}"
    },
}

