"""Localization constants separated from core logic."""

RESEARCH_AREA_ICONS = {
    "physics": "£physics£",
    "engineering": "£engineering£",
    "society": "£society£",
}

LOCALIZATION_STRINGS = {
    "english": {
        "title": "Technology Tree",
        "top_level": "Maximum Level Reached",
        "requires": "Requires",
        "tier_label": "Tier:",
        "already_shown": "already shown above",
        "folded_more": "(and {count} more technologies)",
        "root_children_exceed_limit": "Root direct children exceed global display limit; cannot display tree",
        "global_overflow_reached": "(and {count} more technologies hidden globally)",
        "msg_start_generation": "Generating technology tree MOD...",
        "msg_parsing_save": "Parsing save context...",
        "msg_counting_tree": "Computing technology tree sizes...",
        "msg_evaluating_eligibility": "Evaluating save-driven eligibility...",
        "msg_enabled_mods_count": "Enabled MOD count: {count}",
        "msg_missing_mod_dirs": "Notice: {count} enabled MOD directories are missing",
        "msg_mods_with_new_techs": "Notice: {count} enabled MOD(s) added technologies",
        "warn_missing_dlc_load": "Warning: dlc_load.json not found: {path}",
        "warn_read_dlc_load_failed": "Warning: failed to read dlc_load.json: {error}",
        "warn_write_file_failed": "Warning: cannot write file {file}: {error}",
        "warn_tech_parse_summary": "Notice: scanned {total} tech files; ok={ok}; failed={failed} (showing {shown}, suppressed {suppressed})",
        "warn_tech_parse_failure_example": "  Tech parse failed: {path} — {error}",
        "warn_loc_parse_summary": "Notice: scanned {total} localisation files; ok={ok}; failed={failed} (showing {shown}, suppressed {suppressed})",
        "warn_loc_parse_failure_example": "  Localisation parse failed: {path} — {error}",
        "warn_read_file_failed_summary": "Warning: failed to read {failed} file(s) (showing {shown}, suppressed {suppressed})",
        "warn_read_file_failed_example": "  Read failed: {path} — {error}",
        "warn_missing_descriptions": "Warning: {lang} language has {count} technologies missing descriptions",
        "stats_header": "Generation Statistics:",
        "stats_total": "Total techs: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localized ({lang}): {count}",
        "stats_overlong": "Overlong trees (>{threshold} successors): {count} — not displayed in game",
        "overbreadth_zero": "Over-breadth roots: 0 (T={threshold})",
        "overbreadth_list_header": "Over-breadth roots list (direct children > T):",
        "overbreadth_entry": "  {tech_id}  (children={child_count} > T={threshold})",
        "overbreadth_truncated": "  ... ({remaining} more)",
        "msg_generation_done": "Generation finished!",
        "msg_detecting_cycles": "Detecting technology circular dependencies...",
        "msg_cycles_found": "Found {count} cycle(s):",
        "msg_self_loops_header": "  Self loops ({count}):",
        "msg_complex_loops_header": "  Complex cycles ({count}):",
        "msg_cycle_entry": "    Cycle {index}: {cycle}",
        "msg_no_cycles": "No circular dependencies found.",
        "ui_app_title": "Stellaris Tech Tree Generator",
        "ui_btn_generate": "Generate Tech Tree",
        "ui_btn_generating": "Generating...",
        "ui_btn_save_config": "Save Config",
        "ui_log_loaded_config": "Loaded config: {path}",
        "ui_log_config_not_found": "Config file not found: {path}",
        "ui_log_autodetect_start": "First run or missing paths detected; auto-detecting...",
        "ui_log_autodetect_done": "Auto-detect complete, found {count} path(s)",
        "ui_log_no_config_path": "Config path not set; cannot save.",
        "ui_log_save_failed": "Failed to save config: {error}",
        "ui_log_config_saved": "Saved config: {path}",
        "ui_status_autodetecting": "Auto-detecting paths...",
        "ui_status_paths_ok": "Required paths detected",
        "ui_status_steam_ok": "Steam path detected",
        "ui_status_game_ok": "Game path detected",
        "ui_status_need_manual_paths": "Please configure paths manually",
        "ui_msgbox_title_save_failed": "Save Failed",
        "ui_msgbox_body_save_failed": "Unable to write config file: {error}",
        "ui_msgbox_title_config_error": "Configuration Error",
        "ui_msgbox_title_done": "Done",
        "ui_msgbox_body_generation_done": "Tech tree generation completed!",
        "ui_msgbox_title_incomplete": "Incomplete",
        "ui_msgbox_body_generation_incomplete": "Generation incomplete:\n{details}",
        "ui_msgbox_title_cancelled": "Cancelled",
        "ui_msgbox_body_generation_cancelled": "Generation cancelled.",
        "ui_msgbox_title_error": "Error",
        "ui_msgbox_body_generation_failed": "Generation failed: {error}",
        "ui_msgbox_title_unsupported_save_format": "Unsupported Save Format",
        "ui_msgbox_body_unsupported_save_format": "The selected save file cannot be parsed: {error}",
        "ui_btn_autodetect_all": "Auto-Detect All Paths",
        "ui_btn_browse": "Browse...",
        "ui_btn_autodetect": "Auto-Detect",
        "ui_dialog_title_choose_base_game_dir": "Select Stellaris install directory",
        "ui_dialog_title_choose_workshop_dir": "Select Steam Workshop directory",
        "ui_dialog_title_choose_launcher_db": "Select launcher-v2.sqlite",
        "ui_dialog_title_choose_local_mod_dir": "Select local MOD directory",
        "ui_dialog_title_choose_save_file": "Select Stellaris save file",
        "ui_dialog_title_choose_empire": "Choose player empire",
        "ui_dialog_body_choose_empire": "The save has multiple player empires. Select one country id:",
        "ui_file_filter_all": "All Files (*)",
        "ui_file_filter_json": "JSON Files (*.json);;All Files (*)",
        "ui_file_filter_sqlite": "SQLite Database Files (*.sqlite *.db);;All Files (*)",
        "ui_file_filter_save": "Stellaris Save Files (*.sav);;All Files (*)",
        "ui_tab_paths": "Paths",
        "ui_tab_localization": "Localization",
        "ui_tab_display": "Display",
        "ui_label_base_game_path": "Game install directory",
        "ui_label_workshop_path": "Workshop directory",
        "ui_label_paths_launcher_db_path": "Launcher DB (launcher-v2.sqlite)",
        "ui_label_local_mod_path_optional": "Local MOD directory (optional)",
        "ui_label_language": "Language",
        "ui_label_max_children": "Max children per node (0 = unlimited)",
        "ui_label_max_depth": "Max tree depth (0 = unlimited)",
        "ui_label_max_nodes": "Max displayed nodes (0 = unlimited)",
        "ui_tooltip_path_not_set": "Path not set",
        "ui_tooltip_path_valid": "Path exists: {path}",
        "ui_tooltip_path_missing": "Path not found: {path}",
        "ui_error_missing_required_paths": "Missing required fields: {fields}",
        "ui_field_base_game_path": "Game install directory",
        "ui_field_workshop_path": "Workshop directory",
        "ui_field_launcher_db_path": "Launcher DB (launcher-v2.sqlite)",
        "ui_worker_generation_cancelled": "Generation cancelled.",
        "ui_worker_generation_incomplete": "Generation did not complete.",
        "ui_error_launcher_db_missing_database_path": "Launcher DB path is not set. Set paths.launcher_db_path to the launcher-v2.sqlite file.",
        "ui_error_launcher_db_empty_database_path": "Launcher DB path is empty. Set paths.launcher_db_path to the launcher-v2.sqlite file.",
        "ui_error_launcher_db_missing_database": "Launcher DB not found: {path}. Set paths.launcher_db_path to the launcher-v2.sqlite file.",
        "ui_error_launcher_db_not_a_file": "Launcher DB path is not a file: {path}. Set paths.launcher_db_path to the launcher-v2.sqlite file.",
        "ui_error_launcher_db_locked": "Launcher DB is locked: {path} ({reason}). Close Paradox Launcher or wait for it to finish writing, then retry.",
        "ui_error_launcher_db_open_failed": "Failed to open launcher DB: {path} ({reason}). Check file permissions and verify paths.launcher_db_path points to launcher-v2.sqlite.",
        "ui_error_launcher_db_read_failed": "Failed to read launcher DB: {path} ({reason}). Verify the launcher-v2.sqlite file is readable.",
        "ui_error_launcher_db_corrupt": "Launcher DB is corrupt: {path} ({reason}). Point paths.launcher_db_path to a valid launcher-v2.sqlite file.",
        "ui_error_launcher_db_query_failed": "Launcher DB query failed: {path} ({reason}). Verify launcher-v2.sqlite is valid and not being modified.",
        "ui_error_launcher_db_schema_missing_table": "Launcher DB schema drift: missing table '{table}' in {path}. Verify launcher-v2.sqlite matches the current launcher format.",
        "ui_error_launcher_db_schema_missing_columns": "Launcher DB schema drift: missing required columns in '{table}' table in {path}. Verify launcher-v2.sqlite matches the current launcher format.",
        "ui_error_launcher_db_no_active_playset": "No active playset found in launcher DB: {path}. Open Paradox Launcher, select an active playset, and retry.",
        "ui_error_technology_swap_collision": "technology_swap collision: {collisions}. Multiple base tech ids resolved to the same active display id.",
        "error_generation_exception": "Error during generation: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "simp_chinese": {
        "title": "科技树",
        "top_level": "已达到顶级",
        "requires": "还需",
        "tier_label": "级别:",
        "already_shown": "已在上方展示",
        "folded_more": "(后续还有{count}个科技)",
        "root_children_exceed_limit": "此科技直接子科技数量超过上限，无法展示此树",
        "global_overflow_reached": "(后续还有{count}个科技)",
        "msg_start_generation": "正在生成科技树MOD...",
        "msg_parsing_save": "正在解析存档上下文...",
        "msg_counting_tree": "正在统计科技树规模...",
        "msg_evaluating_eligibility": "正在评估存档驱动的可用性...",
        "msg_enabled_mods_count": "启用MOD数量: {count}",
        "msg_missing_mod_dirs": "提示: 有 {count} 个启用MOD目录缺失",
        "msg_mods_with_new_techs": "提示: 有 {count} 个启用MOD有新增科技",
        "warn_missing_dlc_load": "警告: 找不到 dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "警告: 读取 dlc_load.json 失败: {error}",
        "warn_write_file_failed": "警告：无法写入文件 {file}: {error}",
        "warn_tech_parse_summary": "提示: 扫描科技文件 {total} 个；成功 {ok}；失败 {failed}（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_tech_parse_failure_example": "  科技解析失败: {path} — {error}",
        "warn_loc_parse_summary": "提示: 扫描本地化文件 {total} 个；成功 {ok}；失败 {failed}（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_loc_parse_failure_example": "  本地化解析失败: {path} — {error}",
        "warn_read_file_failed_summary": "警告: 读取文件失败 {failed} 个（展示 {shown} 条，省略 {suppressed} 条）",
        "warn_read_file_failed_example": "  读取失败: {path} — {error}",
        "warn_missing_descriptions": "警告: {lang} 语言有 {count} 个科技缺失描述",
        "stats_header": "生成统计:",
        "stats_total": "科技总数: {total} (本体: {base}, MOD: {mod})",
        "stats_localization": "本地化({lang}): {count}个",
        "stats_overlong": "超长科技树(>{threshold} 后续科技) 数量: {count} —— 游戏内不予展示",
        "overbreadth_zero": "超宽根节点: 0 (T={threshold})",
        "overbreadth_list_header": "超宽根节点列表 (直接子科技 > T):",
        "overbreadth_entry": "  {tech_id}  (子科技数={child_count} > T={threshold})",
        "overbreadth_truncated": "  ... (剩余 {remaining} 个)",
        "msg_generation_done": "生成完成！",
        "msg_detecting_cycles": "正在检测科技循环依赖...",
        "msg_cycles_found": "发现 {count} 个循环依赖:",
        "msg_self_loops_header": "  自循环科技 ({count}个):",
        "msg_complex_loops_header": "  复杂循环 ({count}个):",
        "msg_cycle_entry": "    循环 {index}: {cycle}",
        "msg_no_cycles": "未发现循环依赖。",
        "ui_app_title": "Stellaris 科技树生成器",
        "ui_btn_generate": "生成科技树",
        "ui_btn_generating": "生成中...",
        "ui_btn_save_config": "保存配置",
        "ui_log_loaded_config": "已加载配置: {path}",
        "ui_log_config_not_found": "未找到配置文件: {path}",
        "ui_log_autodetect_start": "检测到首次运行或路径未配置，正在自动检测...",
        "ui_log_autodetect_done": "自动检测完成，找到 {count} 个路径",
        "ui_log_no_config_path": "未设置配置路径，无法保存。",
        "ui_log_save_failed": "保存配置失败: {error}",
        "ui_log_config_saved": "已保存配置: {path}",
        "ui_status_autodetecting": "正在自动检测路径...",
        "ui_status_paths_ok": "已检测到必要路径",
        "ui_status_steam_ok": "已检测到 Steam 路径",
        "ui_status_game_ok": "已检测到本体路径",
        "ui_status_need_manual_paths": "请手动配置路径",
        "ui_msgbox_title_save_failed": "保存失败",
        "ui_msgbox_body_save_failed": "无法写入配置文件：{error}",
        "ui_msgbox_title_config_error": "配置错误",
        "ui_msgbox_title_done": "完成",
        "ui_msgbox_body_generation_done": "科技树生成完成！",
        "ui_msgbox_title_incomplete": "未完成",
        "ui_msgbox_body_generation_incomplete": "生成未完成：\n{details}",
        "ui_msgbox_title_cancelled": "已取消",
        "ui_msgbox_body_generation_cancelled": "生成已取消。",
        "ui_msgbox_title_error": "错误",
        "ui_msgbox_body_generation_failed": "生成失败：{error}",
        "ui_msgbox_title_unsupported_save_format": "不支持的存档格式",
        "ui_msgbox_body_unsupported_save_format": "所选存档无法解析：{error}",
        "ui_btn_autodetect_all": "自动检测所有路径",
        "ui_btn_browse": "浏览...",
        "ui_btn_autodetect": "自动检测",
        "ui_dialog_title_choose_base_game_dir": "选择群星本体安装目录",
        "ui_dialog_title_choose_workshop_dir": "选择 Steam 创意工坊目录",
        "ui_dialog_title_choose_launcher_db": "选择 launcher-v2.sqlite",
        "ui_dialog_title_choose_local_mod_dir": "选择本地 MOD 目录",
        "ui_dialog_title_choose_save_file": "选择群星存档文件",
        "ui_dialog_title_choose_empire": "选择玩家帝国",
        "ui_dialog_body_choose_empire": "该存档包含多个玩家帝国，请选择国家 ID：",
        "ui_file_filter_all": "所有文件 (*)",
        "ui_file_filter_json": "JSON 文件 (*.json);;所有文件 (*)",
        "ui_file_filter_sqlite": "SQLite 数据库文件 (*.sqlite *.db);;所有文件 (*)",
        "ui_file_filter_save": "群星存档 (*.sav);;所有文件 (*)",
        "ui_tab_paths": "路径设置",
        "ui_tab_localization": "本地化设置",
        "ui_tab_display": "显示设置",
        "ui_label_base_game_path": "本体安装目录",
        "ui_label_workshop_path": "创意工坊目录",
        "ui_label_paths_launcher_db_path": "启动器数据库（launcher-v2.sqlite）",
        "ui_label_local_mod_path_optional": "本地 MOD 目录（可选）",
        "ui_label_language": "语言",
        "ui_label_max_children": "最大子节点数 (0 = 无限制)",
        "ui_label_max_depth": "最大树深度 (0 = 无限制)",
        "ui_label_max_nodes": "最大显示节点数 (0 = 无限制)",
        "ui_tooltip_path_not_set": "未设置路径",
        "ui_tooltip_path_valid": "路径有效: {path}",
        "ui_tooltip_path_missing": "路径不存在: {path}",
        "ui_error_missing_required_paths": "路径设置缺少必填项: {fields}",
        "ui_field_base_game_path": "本体安装目录",
        "ui_field_workshop_path": "创意工坊目录",
        "ui_field_launcher_db_path": "启动器数据库路径（launcher-v2.sqlite）",
        "ui_worker_generation_cancelled": "生成已取消。",
        "ui_worker_generation_incomplete": "生成未完成。",
        "ui_error_technology_swap_collision": "technology_swap 冲突: {collisions}。多个基础科技解析到同一个显示科技 id。",
        "error_generation_exception": "生成过程中出现错误: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "french": {
        "title": "Arbre Technologique",
        "top_level": "Niveau maximum atteint",
        "requires": "Requiert",
        "tier_label": "Niveau:",
        "already_shown": "déjà affiché ci-dessus",
        "msg_start_generation": "Génération du MOD d'arbre technologique...",
        "msg_counting_tree": "Calcul de la taille des arbres technologiques...",
        "msg_enabled_mods_count": "Nombre de MODs activés : {count}",
        "msg_missing_mod_dirs": "Remarque : {count} dossiers de MOD activés manquent",
        "msg_mods_with_new_techs": "Remarque : {count} MOD(s) ont ajouté des technologies",
        "warn_missing_dlc_load": "Avertissement : dlc_load.json introuvable : {path}",
        "warn_read_dlc_load_failed": "Avertissement : échec de lecture de dlc_load.json : {error}",
        "warn_write_file_failed": "Avertissement : impossible d'écrire le fichier {file} : {error}",
        "warn_missing_descriptions": "Avertissement : la langue {lang} a {count} technologies sans description",
        "stats_header": "Statistiques de génération :",
        "stats_total": "Total technologies : {total} (Base : {base}, MOD : {mod})",
        "stats_localization": "Localisé ({lang}) : {count}",
        "stats_overlong": "Arbres trop longs (>{threshold} successeurs) : {count} — non affichés en jeu",
        "msg_generation_done": "Génération terminée !",
        "msg_detecting_cycles": "Détection des dépendances circulaires...",
        "msg_cycles_found": "Trouvé {count} cycle(s) :",
        "msg_self_loops_header": "  Boucles simples ({count}) :",
        "msg_complex_loops_header": "  Cycles complexes ({count}) :",
        "msg_cycle_entry": "    Cycle {index}: {cycle}",
        "msg_no_cycles": "Aucun cycle détecté.",
        "error_generation_exception": "Erreur pendant la génération : {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "german": {
        "title": "Technologiebaum",
        "top_level": "Maximale Stufe erreicht",
        "requires": "Benötigt",
        "tier_label": "Stufe:",
        "already_shown": "oben bereits angezeigt",
        "msg_start_generation": "Generiere Technologiebaum-MOD...",
        "msg_counting_tree": "Berechne Technologiebaum-Größen...",
        "msg_enabled_mods_count": "Aktivierte MOD-Anzahl: {count}",
        "msg_missing_mod_dirs": "Hinweis: {count} aktivierte MOD-Verzeichnisse fehlen",
        "msg_mods_with_new_techs": "Hinweis: {count} MOD(s) fügten Technologien hinzu",
        "warn_missing_dlc_load": "Warnung: dlc_load.json nicht gefunden: {path}",
        "warn_read_dlc_load_failed": "Warnung: Lesen von dlc_load.json fehlgeschlagen: {error}",
        "warn_write_file_failed": "Warnung: Datei {file} kann nicht geschrieben werden: {error}",
        "warn_missing_descriptions": "Warnung: Sprache {lang} hat {count} Technologien ohne Beschreibung",
        "stats_header": "Generierungsstatistiken:",
        "stats_total": "Technologien gesamt: {total} (Basis: {base}, MOD: {mod})",
        "stats_localization": "Lokalisiert ({lang}): {count}",
        "stats_overlong": "Zu lange Bäume (>{threshold} Nachfolger): {count} — nicht im Spiel angezeigt",
        "msg_generation_done": "Generierung abgeschlossen!",
        "msg_detecting_cycles": "Suche nach zyklischen Abhängigkeiten...",
        "msg_cycles_found": "{count} Zyklen gefunden:",
        "msg_self_loops_header": "  Selbstschleifen ({count}):",
        "msg_complex_loops_header": "  Komplexe Zyklen ({count}):",
        "msg_cycle_entry": "    Zyklus {index}: {cycle}",
        "msg_no_cycles": "Keine Zyklen gefunden.",
        "error_generation_exception": "Fehler während der Generierung: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "spanish": {
        "title": "Árbol Tecnológico",
        "top_level": "Nivel Máximo Alcanzado",
        "requires": "Requiere",
        "tier_label": "Nivel:",
        "already_shown": "ya mostrado arriba",
        "msg_start_generation": "Generando MOD del árbol tecnológico...",
        "msg_counting_tree": "Calculando tamaños del árbol tecnológico...",
        "msg_enabled_mods_count": "Cantidad de MODs habilitados: {count}",
        "msg_missing_mod_dirs": "Aviso: faltan {count} directorios de MOD habilitados",
        "msg_mods_with_new_techs": "Aviso: {count} MOD(s) añadieron tecnologías",
        "warn_missing_dlc_load": "Advertencia: no se encontró dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Advertencia: fallo al leer dlc_load.json: {error}",
        "warn_write_file_failed": "Advertencia: no se puede escribir el archivo {file}: {error}",
        "warn_missing_descriptions": "Advertencia: el idioma {lang} tiene {count} tecnologías sin descripción",
        "stats_header": "Estadísticas de generación:",
        "stats_total": "Tecnologías totales: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localizado ({lang}): {count}",
        "stats_overlong": "Árboles demasiado largos (>{threshold} sucesoras): {count} — no se muestran en el juego",
        "msg_generation_done": "¡Generación finalizada!",
        "msg_detecting_cycles": "Detectando dependencias cíclicas...",
        "msg_cycles_found": "Encontrado(s) {count} ciclo(s):",
        "msg_self_loops_header": "  Bucles simples ({count}):",
        "msg_complex_loops_header": "  Ciclos complejos ({count}):",
        "msg_cycle_entry": "    Ciclo {index}: {cycle}",
        "msg_no_cycles": "No se encontraron ciclos.",
        "error_generation_exception": "Error durante la generación: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "russian": {
        "title": "Древо технологий",
        "top_level": "Достигнут максимальный уровень",
        "requires": "Требуется",
        "tier_label": "Уровень:",
        "already_shown": "уже показано выше",
        "msg_start_generation": "Генерация мода древа технологий...",
        "msg_counting_tree": "Подсчет размеров древ технологий...",
        "msg_enabled_mods_count": "Количество активных модов: {count}",
        "msg_missing_mod_dirs": "Примечание: отсутствует {count} каталог(ов) активных модов",
        "msg_mods_with_new_techs": "Примечание: {count} мод(ов) добавили технологии",
        "warn_missing_dlc_load": "Предупреждение: не найден dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Предупреждение: ошибка чтения dlc_load.json: {error}",
        "warn_write_file_failed": "Предупреждение: не удалось записать файл {file}: {error}",
        "warn_missing_descriptions": "Предупреждение: язык {lang} — {count} технологий без описания",
        "stats_header": "Статистика генерации:",
        "stats_total": "Всего технологий: {total} (База: {base}, Моды: {mod})",
        "stats_localization": "Локализовано ({lang}): {count}",
        "stats_overlong": "Слишком длинные деревья (>{threshold} потомков): {count} — не показываются в игре",
        "msg_generation_done": "Генерация завершена!",
        "msg_detecting_cycles": "Поиск циклических зависимостей...",
        "msg_cycles_found": "Найдено циклов: {count}",
        "msg_self_loops_header": "  Самоциклы ({count}):",
        "msg_complex_loops_header": "  Сложные циклы ({count}):",
        "msg_cycle_entry": "    Цикл {index}: {cycle}",
        "msg_no_cycles": "Циклов не обнаружено.",
        "error_generation_exception": "Ошибка в ходе генерации: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "korean": {
        "title": "기술 트리",
        "top_level": "최대 단계 도달",
        "requires": "요구",
        "tier_label": "단계:",
        "already_shown": "위에 이미 표시됨",
        "msg_start_generation": "기술 트리 MOD 생성 중...",
        "msg_counting_tree": "기술 트리 규모 계산 중...",
        "msg_enabled_mods_count": "활성 MOD 수: {count}",
        "msg_missing_mod_dirs": "알림: 활성 MOD 디렉터리 {count}개 누락",
        "msg_mods_with_new_techs": "알림: {count}개 MOD가 기술을 추가함",
        "warn_missing_dlc_load": "경고: dlc_load.json 을 찾을 수 없음: {path}",
        "warn_read_dlc_load_failed": "경고: dlc_load.json 읽기 실패: {error}",
        "warn_write_file_failed": "경고: 파일 {file} 을(를) 쓸 수 없음: {error}",
        "warn_missing_descriptions": "경고: {lang} 언어 기술 {count}개 설명 누락",
        "stats_header": "생성 통계:",
        "stats_total": "기술 총계: {total} (본체: {base}, MOD: {mod})",
        "stats_localization": "로컬라이즈됨 ({lang}): {count}",
        "stats_overlong": "너무 긴 트리 (>{threshold} 후속): {count} — 게임에서 표시 안 함",
        "msg_generation_done": "생성 완료!",
        "msg_detecting_cycles": "순환 의존성 탐지 중...",
        "msg_cycles_found": "순환 {count}개 발견:",
        "msg_self_loops_header": "  자기 순환 ({count})",
        "msg_complex_loops_header": "  복잡한 순환 ({count})",
        "msg_cycle_entry": "    순환 {index}: {cycle}",
        "msg_no_cycles": "순환 없음.",
        "error_generation_exception": "생성 중 오류 발생: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "japanese": {
        "title": "技術ツリー",
        "top_level": "最大レベルに到達",
        "requires": "必要",
        "tier_label": "レベル:",
        "already_shown": "上で既に表示済み",
        "msg_start_generation": "技術ツリーMOD生成中...",
        "msg_counting_tree": "技術ツリー規模を計算中...",
        "msg_enabled_mods_count": "有効MOD数: {count}",
        "msg_missing_mod_dirs": "注意: 有効なMODディレクトリ {count} 個が見つかりません",
        "msg_mods_with_new_techs": "注意: {count} 個のMODが技術を追加しました",
        "warn_missing_dlc_load": "警告: dlc_load.json が見つかりません: {path}",
        "warn_read_dlc_load_failed": "警告: dlc_load.json の読み込みに失敗: {error}",
        "warn_write_file_failed": "警告: ファイル {file} に書き込めません: {error}",
        "warn_missing_descriptions": "警告: 言語 {lang} で {count} 技術の説明が不足",
        "stats_header": "生成統計:",
        "stats_total": "技術総数: {total} (本体: {base}, MOD: {mod})",
        "stats_localization": "ローカライズ済 ({lang}): {count}",
        "stats_overlong": "長すぎるツリー (>{threshold} 派生): {count} — ゲーム内では表示されません",
        "msg_generation_done": "生成完了！",
        "msg_detecting_cycles": "循環依存を検出中...",
        "msg_cycles_found": "{count} 個の循環を検出:",
        "msg_self_loops_header": "  自己循環 ({count})",
        "msg_complex_loops_header": "  複雑な循環 ({count})",
        "msg_cycle_entry": "    循環 {index}: {cycle}",
        "msg_no_cycles": "循環は見つかりませんでした。",
        "error_generation_exception": "生成中にエラーが発生しました: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "polish": {
        "title": "Drzewo Technologii",
        "top_level": "Osiągnięto maksymalny poziom",
        "requires": "Wymaga",
        "tier_label": "Poziom:",
        "already_shown": "już pokazano powyżej",
        "msg_start_generation": "Generowanie moda drzewa technologii...",
        "msg_counting_tree": "Obliczanie rozmiarów drzew technologii...",
        "msg_enabled_mods_count": "Liczba aktywnych modów: {count}",
        "msg_missing_mod_dirs": "Uwaga: brak {count} katalogów aktywnych modów",
        "msg_mods_with_new_techs": "Uwaga: {count} mod(y) dodały technologie",
        "warn_missing_dlc_load": "Ostrzeżenie: nie znaleziono dlc_load.json: {path}",
        "warn_read_dlc_load_failed": "Ostrzeżenie: błąd odczytu dlc_load.json: {error}",
        "warn_write_file_failed": "Ostrzeżenie: nie można zapisać pliku {file}: {error}",
        "warn_missing_descriptions": "Ostrzeżenie: język {lang} ma {count} technologii bez opisu",
        "stats_header": "Statystyki generowania:",
        "stats_total": "Łącznie technologii: {total} (Podstawa: {base}, Mody: {mod})",
        "stats_localization": "Zlokalizowano ({lang}): {count}",
        "stats_overlong": "Zbyt długie drzewa (>{threshold} następców): {count} — niewyświetlane w grze",
        "msg_generation_done": "Generowanie zakończone!",
        "msg_detecting_cycles": "Wykrywanie zależności cyklicznych...",
        "msg_cycles_found": "Znaleziono cykli: {count}",
        "msg_self_loops_header": "  Pętle własne ({count}):",
        "msg_complex_loops_header": "  Złożone cykle ({count}):",
        "msg_cycle_entry": "    Cykl {index}: {cycle}",
        "msg_no_cycles": "Nie znaleziono cykli.",
        "error_generation_exception": "Błąd podczas generowania: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
    "braz_por": {
        "title": "Árvore de Tecnologia",
        "top_level": "Nível Máximo Atingido",
        "requires": "Requer",
        "tier_label": "Nível:",
        "already_shown": "já mostrado acima",
        "msg_start_generation": "Gerando MOD da árvore de tecnologia...",
        "msg_counting_tree": "Calculando tamanhos da árvore de tecnologia...",
        "msg_enabled_mods_count": "Quantidade de MODs ativos: {count}",
        "msg_missing_mod_dirs": "Aviso: {count} diretórios de MOD ativos ausentes",
        "msg_mods_with_new_techs": "Aviso: {count} MOD(s) adicionaram tecnologias",
        "warn_missing_dlc_load": "Aviso: dlc_load.json não encontrado: {path}",
        "warn_read_dlc_load_failed": "Aviso: falha ao ler dlc_load.json: {error}",
        "warn_write_file_failed": "Aviso: não é possível gravar o arquivo {file}: {error}",
        "warn_missing_descriptions": "Aviso: idioma {lang} tem {count} tecnologias sem descrição",
        "stats_header": "Estatísticas de geração:",
        "stats_total": "Total de tecnologias: {total} (Base: {base}, MOD: {mod})",
        "stats_localization": "Localizado ({lang}): {count}",
        "stats_overlong": "Árvores muito longas (>{threshold} sucessoras): {count} — não exibidas no jogo",
        "msg_generation_done": "Geração concluída!",
        "msg_detecting_cycles": "Detectando dependências circulares...",
        "msg_cycles_found": "Encontrados {count} ciclo(s)",
        "msg_self_loops_header": "  Auto-loops ({count})",
        "msg_complex_loops_header": "  Ciclos complexos ({count})",
        "msg_cycle_entry": "    Ciclo {index}: {cycle}",
        "msg_no_cycles": "Nenhum ciclo encontrado.",
        "error_generation_exception": "Erro durante a geração: {error}",
        "msg_self_loop_entry": "    {tech} -> {tech}",
    },
}

_SETTINGS_METADATA_DEFAULTS_ENGLISH = {
    "ui_tab_output": "Output",
    "ui_tab_advanced": "Advanced",
    "ui_action_apply_json": "Apply JSON",
    "ui_label_schema_version": "Schema version",
    "ui_help_schema_version": "Version of the settings schema.",
    "ui_help_base_game_path": "Directory where Stellaris is installed.",
    "ui_help_workshop_path": "Steam Workshop directory for Stellaris mods.",
    "ui_help_paths_launcher_db_path": "Path to launcher-v2.sqlite used to resolve enabled mods.",
    "ui_help_local_mod_path": "Optional local mod directory outside Steam Workshop.",
    "ui_label_paths_steam_app_id": "Steam app ID",
    "ui_help_paths_steam_app_id": "Workshop app ID used for autodetection.",
    "ui_label_paths_game_directory_name": "Game directory name",
    "ui_help_paths_game_directory_name": "Directory name under steamapps/common used for autodetection.",
    "ui_label_paths_user_data_subpath_components": "User data subpath components",
    "ui_help_paths_user_data_subpath_components": "Subpath components under Documents for user data autodetection.",
    "ui_label_paths_launcher_db_filename": "Launcher database filename",
    "ui_help_paths_launcher_db_filename": "Filename searched under user data path for launcher database.",
    "ui_label_paths_local_mod_directory_name": "Local mod directory name",
    "ui_help_paths_local_mod_directory_name": "Directory searched under user data path for local mods.",
    "ui_label_file_indexing_technology_root": "Technology root (relative)",
    "ui_help_file_indexing_technology_root": "Relative path under each source root scanned for technology files.",
    "ui_label_file_indexing_technology_glob": "Technology file glob",
    "ui_help_file_indexing_technology_glob": "Glob pattern used under technology_root when indexing technology files.",
    "ui_label_file_indexing_localisation_root": "Localisation root (relative)",
    "ui_help_file_indexing_localisation_root": "Relative path under each source root scanned for localisation files.",
    "ui_label_file_indexing_localisation_glob": "Localisation file glob",
    "ui_help_file_indexing_localisation_glob": "Glob pattern used under localisation_root when indexing localisation files.",
    "ui_label_file_indexing_localisation_replace_prefix": "Localisation replace prefix",
    "ui_help_file_indexing_localisation_replace_prefix": "Localisation files under this prefix are loaded in a late phase.",
    "ui_label_load_order_multi_active_playset_selection_policy": "Active playset selection policy",
    "ui_help_load_order_multi_active_playset_selection_policy": "How to choose a playset when multiple active playsets are active.",
    "ui_help_language": "Language used for generated localisation output.",
    "ui_help_max_children": "Maximum children shown per node (0 means unlimited).",
    "ui_help_max_depth": "Maximum tree depth to render (0 means unlimited).",
    "ui_help_max_nodes": "Maximum nodes rendered in one tree (0 means unlimited).",
    "ui_label_display_max_prereq_display": "Max additional prerequisites",
    "ui_help_display_max_prereq_display": "Maximum extra prerequisites shown before the ellipsis.",
    "ui_label_decode_preferred_encodings": "Preferred input encodings",
    "ui_help_decode_preferred_encodings": "Tried first when decoding text files.",
    "ui_label_decode_fallback_encodings": "Fallback input encodings",
    "ui_help_decode_fallback_encodings": "Tried after preferred encodings fail.",
    "ui_label_decode_replacement_encoding": "Replacement encoding",
    "ui_help_decode_replacement_encoding": "Used for replacement-mode decode when all attempts fail.",
    "ui_label_decode_on_failure": "Decode failure policy",
    "ui_help_decode_on_failure": "Behavior when all configured encodings fail.",
    "ui_label_save_reader_max_member_uncompressed_size_bytes": "Save ZIP per-member uncompressed cap (bytes)",
    "ui_help_save_reader_max_member_uncompressed_size_bytes": "Reject ZIP members larger than this many bytes.",
    "ui_label_save_reader_max_total_uncompressed_size_bytes": "Save ZIP total uncompressed cap (bytes)",
    "ui_help_save_reader_max_total_uncompressed_size_bytes": "Reject ZIP archives whose total uncompressed size exceeds this.",
    "ui_label_save_reader_max_parse_diagnostics_per_member": "Max parse diagnostics per member",
    "ui_help_save_reader_max_parse_diagnostics_per_member": "Limit how many parse diagnostics are shown per save member.",
    "ui_label_ingestion_diagnostic_example_limit": "Ingestion diagnostics example limit",
    "ui_help_ingestion_diagnostic_example_limit": "Maximum ingestion parse/decode examples shown per stage.",
    "ui_label_diagnostics_overlong_tree_roots_log_limit": "Over-breadth roots log limit",
    "ui_help_diagnostics_overlong_tree_roots_log_limit": "Maximum over-breadth root entries shown in diagnostics logs (0 means unlimited).",
    "ui_label_yml_targets": "YML output targets",
    "ui_help_yml_targets": "Relative localisation targets generated for each output file.",
    "ui_label_yml_encoding": "YML encoding",
    "ui_help_yml_encoding": "Encoding used when writing localisation YML files.",
    "ui_label_report_encoding": "Report encoding",
    "ui_help_report_encoding": "Encoding used for save eligibility reports.",
    "ui_label_output_eligibility_sample_size": "Eligibility report sample size",
    "ui_help_output_eligibility_sample_size": "How many deterministic examples to include per eligibility report section.",
    "ui_label_output_eligibility_unknown_warning_threshold": "Eligibility unknown-warning threshold",
    "ui_help_output_eligibility_unknown_warning_threshold": "Warn when unknown potential exclusions reach this count (0 disables warning).",
    "ui_label_on_write_error": "On write error",
    "ui_help_on_write_error": "Behavior when writing one output target fails.",
    "ui_label_on_existing_file": "On existing file",
    "ui_help_on_existing_file": "Behavior when the output file already exists.",
    "ui_label_progress_milestone_save_parse_start": "SAVE_PARSE start progress",
    "ui_help_progress_milestone_save_parse_start": "Progress milestone for SAVE_PARSE start.",
    "ui_label_progress_milestone_save_parse_parse": "SAVE_PARSE parse progress",
    "ui_help_progress_milestone_save_parse_parse": "Progress milestone for SAVE_PARSE parse.",
    "ui_label_progress_milestone_load_order": "LOAD_ORDER progress",
    "ui_help_progress_milestone_load_order": "Progress milestone for LOAD_ORDER.",
    "ui_label_progress_milestone_relations": "RELATIONS progress",
    "ui_help_progress_milestone_relations": "Progress milestone for RELATIONS.",
    "ui_label_progress_milestone_ingest_l10n": "INGEST_L10N progress",
    "ui_help_progress_milestone_ingest_l10n": "Progress milestone for INGEST_L10N.",
    "ui_label_progress_milestone_render": "RENDER progress",
    "ui_help_progress_milestone_render": "Progress milestone for RENDER.",
    "ui_label_progress_milestone_cycles": "CYCLES progress",
    "ui_help_progress_milestone_cycles": "Progress milestone for CYCLES.",
    "ui_label_progress_milestone_write_output": "WRITE_OUTPUT progress",
    "ui_help_progress_milestone_write_output": "Progress milestone for WRITE_OUTPUT.",
    "ui_label_progress_milestone_done": "DONE progress",
    "ui_help_progress_milestone_done": "Progress milestone for DONE.",
    "ui_label_file_indexing": "File indexing",
    "ui_help_file_indexing": "Settings for scanning/indexing technology and localisation files.",
    "ui_label_load_order": "Load order",
    "ui_help_load_order": "Settings for resolving enabled mods from the launcher database.",
    "ui_label_decode": "Decode settings",
    "ui_help_decode": "Encoding attempts and fallback policy.",
    "ui_label_save_reader": "Save reader",
    "ui_help_save_reader": "Safety caps and diagnostics limits for reading .sav files.",
    "ui_label_ingestion": "Ingestion",
    "ui_help_ingestion": "Limits for ingestion diagnostics example reporting.",
    "ui_label_diagnostics": "Diagnostics",
    "ui_help_diagnostics": "Limits for generator diagnostics and reporting behavior.",
    "ui_help_paths": "Path settings for game data and autodetection.",
    "ui_help_localization": "Localization language and related settings.",
    "ui_help_display": "Display limits and progress display settings.",
    "ui_help_output": "Output file and write-policy settings.",
    "ui_label_progress_milestones": "Progress milestones",
    "ui_help_progress_milestones": "Milestone percentages used by the GUI progress bar.",
}


english_strings = LOCALIZATION_STRINGS.get("english")
if isinstance(english_strings, dict):
    for key, value in _SETTINGS_METADATA_DEFAULTS_ENGLISH.items():
        english_strings.setdefault(key, value)

    for language, language_strings in LOCALIZATION_STRINGS.items():
        if language == "english":
            continue
        for key, value in english_strings.items():
            if key.startswith(("ui_label_", "ui_help_", "ui_tab_", "ui_action_")):
                language_strings.setdefault(key, value)
